src/Entity/Pedido.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PedidoRepository")
 */
class Pedido
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $clienteNombre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $clienteEmail;

    /**
     * @ORM\Column(type="integer")
     */
    private $clienteTelefono;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $clienteDireccion;

    /**
     * @ORM\Column(type="integer")
     */
    private $importe;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $fechaEntrega;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\PedidoProducto", mappedBy="pedido", cascade={"persist", "remove"})
     */
    private $pedidoProductos;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $franjaHoraria;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
        $this->pedidoProductos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClienteNombre(): ?string
    {
        return $this->clienteNombre;
    }

    public function setClienteNombre(string $clienteNombre): self
    {
        $this->clienteNombre = $clienteNombre;

        return $this;
    }

    public function getClienteEmail(): ?string
    {
        return $this->clienteEmail;
    }

    public function setClienteEmail(string $clienteEmail): self
    {
        $this->clienteEmail = $clienteEmail;

        return $this;
    }

    public function getClienteTelefono(): ?int
    {
        return $this->clienteTelefono;
    }

    public function setClienteTelefono(int $clienteTelefono): self
    {
        $this->clienteTelefono = $clienteTelefono;

        return $this;
    }

    public function getClienteDireccion(): ?string
    {
        return $this->clienteDireccion;
    }

    public function setClienteDireccion(string $clienteDireccion): self
    {
        $this->clienteDireccion = $clienteDireccion;

        return $this;
    }

    public function getImporte(): ?int
    {
        return $this->importe;
    }

    public function setImporte(int $importe): self
    {
        $this->importe = $importe;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getFechaEntrega(): ?\DateTimeInterface
    {
        return $this->fechaEntrega;
    }

    public function setFechaEntrega($fechaEntrega): self
    {
        $this->fechaEntrega = $fechaEntrega;

        return $this;
    }

    /**
     * @return Collection|PedidoProducto[]
     */
    public function getPedidoProductos(): Collection
    {
        return $this->pedidoProductos;
    }

    public function addPedidoProducto(PedidoProducto $pedidoProducto): self
    {
        if (!$this->pedidoProductos->contains($pedidoProducto)) {
            $this->pedidoProductos[] = $pedidoProducto;
            $pedidoProducto->setPedido($this);
        }

        return $this;
    }

    public function removePedidoProducto(PedidoProducto $pedidoProducto): self
    {
        if ($this->pedidoProductos->contains($pedidoProducto)) {
            $this->pedidoProductos->removeElement($pedidoProducto);
//            $pedidoProducto->removePedido($this);
        }

        return $this;
    }

    public function getFranjaHoraria(): ?string
    {
        return $this->franjaHoraria;
    }

    public function setFranjaHoraria(?string $franjaHoraria): self
    {
        $this->franjaHoraria = $franjaHoraria;

        return $this;
    }
}

src/Entity/Producto.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductoRepository")
 */
class Producto
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotBlank()
     */
    private $nombre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $descripcion;

    /**
     * @ORM\Column(type="integer")
     */
    private $unidades;

    /**
     * @ORM\Column(type="integer")
     */
    private $precio;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Tienda", inversedBy="productos")
     */
    private $tienda;

    /**
     * Producto constructor.
     *
     * @throws \Exception
     */
    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->descripcion;
    }

    public function setDescripcion(?string $descripcion): self
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    public function getUnidades(): ?int
    {
        return $this->unidades;
    }

    public function setUnidades(?int $unidades): self
    {
        $this->unidades = $unidades;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPrecio(): ?int
    {
        return $this->precio;
    }

    public function getPrecioEuros()
    {
        return ($this->precio)/100;
    }

    /**
     * @param $precio
     *
     * @return Producto
     */
    public function setPrecio($precio): self
    {
        $this->precio = $precio;

        return $this;
    }

    /**
     * @param $precio
     *
     * @throws \Exception
     */
    public function checkAndSetPrecio($precio)
    {
        if (is_numeric($precio))
        {
            $this->setPrecio($precio);
        }
        else {
            throw new \Exception('Error en el precio');
        }
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getTienda(): ?Tienda
    {
        return $this->tienda;
    }

    public function setTienda(?Tienda $tienda): self
    {
        $this->tienda = $tienda;

        return $this;
    }
}

src/Form/PedidoType.php
<?php

namespace App\Form;

use App\Entity\Pedido;
use App\Entity\Producto;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PedidoType extends AbstractType
{
    /** @var EventSubscriberInterface */
    private $subscriber;

    /**
     * PedidoType constructor.
     * @param EventSubscriberInterface $subscriber
     */
    public function __construct(EventSubscriberInterface $subscriber)
    {
        $this->subscriber = $subscriber;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('clienteNombre')
            ->add('clienteEmail')
            ->add('clienteTelefono')
            ->add('clienteDireccion')
            ->add('fechaEntrega')
            ->add('franjaHoraria')
            ->add('producto_1', EntityType::class, [
                'class' => Producto::class,
                'mapped' => false,
                'choice_label' => function (Producto $producto) {
                    return $producto->getNombre().' '.$producto->getPrecioEuros().' €';
                },
            ])
            ->add('producto_cantidad_1', IntegerType::class, [
                'mapped' => false
            ])
            ->add('producto_2', EntityType::class, [
                'class' => Producto::class,
                'mapped' => false,
                'choice_label' => function (Producto $producto) {
                    return $producto->getNombre().' '.$producto->getPrecioEuros().' €';
                },
            ])
            ->add('producto_cantidad_2', IntegerType::class, [
                'mapped' => false
            ])
            ->add('producto_3', EntityType::class, [
                'class' => Producto::class,
                'mapped' => false,
                'choice_label' => function (Producto $producto) {
                    return $producto->getNombre().' '.$producto->getPrecioEuros().' €';
                },
            ])
            ->add('producto_cantidad_3', IntegerType::class, [
                'mapped' => false
            ])
        ;

        $builder->addEventSubscriber($this->subscriber);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Pedido::class,
        ]);
    }
}

src/Controller/PedidoController.php
<?php

namespace App\Controller;

use App\Entity\Pedido;
use App\Form\PedidoType;
use App\Repository\PedidoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/pedido")
 */
class PedidoController extends AbstractController
{
    /**
     * @Route("/", name="pedido_index", methods={"GET"})
     */
    public function index(PedidoRepository $pedidoRepository): Response
    {
        return $this->render('pedido/index.html.twig', [
            'pedidos' => $pedidoRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="pedido_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $pedido = new Pedido();
        $form = $this->createForm(PedidoType::class, $pedido);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($pedido);
            $entityManager->flush();

            return $this->redirectToRoute('pedido_index');
        }

        return $this->render('pedido/new.html.twig', [
            'pedido' => $pedido,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="pedido_show", methods={"GET"})
     */
    public function show(Pedido $pedido): Response
    {
        return $this->render('pedido/show.html.twig', [
            'pedido' => $pedido,
            'pedidoProductos' => $pedido->getPedidoProductos()->getValues()
        ]);
    }

    /**
     * @Route("/{id}/edit", name="pedido_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Pedido $pedido): Response
    {
        $form = $this->createForm(PedidoType::class, $pedido);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('pedido_index', [
                'id' => $pedido->getId(),
            ]);
        }

        return $this->render('pedido/edit.html.twig', [
            'pedido' => $pedido,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="pedido_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Pedido $pedido): Response
    {
        if ($this->isCsrfTokenValid('delete'.$pedido->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($pedido);
            $entityManager->flush();
        }

        return $this->redirectToRoute('pedido_index');
    }
}

templates/pedido/_delete_form.html.twig
<form method="post" action="{{ path('pedido_delete', {'id': pedido.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ pedido.id) }}">
    <button class="btn">Delete</button>
</form>

templates/pedido/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/pedido/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Pedido{% endblock %}

{% block body %}
    <h1>Edit Pedido</h1>

    {{ include('pedido/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('pedido_index') }}">back to list</a>

    {{ include('pedido/_delete_form.html.twig') }}
{% endblock %}

templates/pedido/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pedido index{% endblock %}

{% block body %}
    <h1>Pedido index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>ClienteNombre</th>
                <th>ClienteEmail</th>
                <th>ClienteTelefono</th>
                <th>ClienteDireccion</th>
                <th>Importe</th>
                <th>CreatedAt</th>
                <th>FechaEntrega</th>
                <th>FranjaHoraria</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for pedido in pedidos %}
            <tr>
                <td>{{ pedido.id }}</td>
                <td>{{ pedido.clienteNombre }}</td>
                <td>{{ pedido.clienteEmail }}</td>
                <td>{{ pedido.clienteTelefono }}</td>
                <td>{{ pedido.clienteDireccion }}</td>
                <td>{{ pedido.importe }}</td>
                <td>{{ pedido.createdAt ? pedido.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ pedido.fechaEntrega ? pedido.fechaEntrega|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ pedido.franjaHoraria }}</td>
                <td>
                    <a href="{{ path('pedido_show', {'id': pedido.id}) }}">show</a>
                    <a href="{{ path('pedido_edit', {'id': pedido.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('pedido_new') }}">Create new</a>
{% endblock %}

templates/pedido/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Pedido{% endblock %}

{% block body %}
    <h1>Create new Pedido</h1>

    {{ include('pedido/_form.html.twig') }}

    <a href="{{ path('pedido_index') }}">back to list</a>
{% endblock %}

templates/pedido/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pedido{% endblock %}

{% block body %}
    <h1>Pedido</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ pedido.id }}</td>
            </tr>
            <tr>
                <th>ClienteNombre</th>
                <td>{{ pedido.clienteNombre }}</td>
            </tr>
            <tr>
                <th>ClienteEmail</th>
                <td>{{ pedido.clienteEmail }}</td>
            </tr>
            <tr>
                <th>ClienteTelefono</th>
                <td>{{ pedido.clienteTelefono }}</td>
            </tr>
            <tr>
                <th>ClienteDireccion</th>
                <td>{{ pedido.clienteDireccion }}</td>
            </tr>
            <tr>
                <th>Importe</th>
                <td>{{ pedido.importe }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ pedido.createdAt ? pedido.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>FechaEntrega</th>
                <td>{{ pedido.fechaEntrega ? pedido.fechaEntrega|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>FranjaHoraria</th>
                <td>{{ pedido.franjaHoraria }}</td>
            </tr>
        </tbody>
    </table>

    <table>
        <thead>
            <tr>
                <th>Producto</th>
                <th>Cantidad</th>
                <th>Precio unitario</th>
            </tr>
        </thead>
        <tbody>
            {% for pedidoProducto in pedido.pedidoProductos %}
                <tr>
                    <td>{{ pedidoProducto.producto.id }} - {{ pedidoProducto.producto.nombre }}</td>
                    <td>{{ pedidoProducto.unidades }}</td>
                    <td>{{ pedidoProducto.producto.precioEuros }} €</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('pedido_index') }}">back to list</a>

    <a href="{{ path('pedido_edit', {'id': pedido.id}) }}">edit</a>

    {{ include('pedido/_delete_form.html.twig') }}
{% endblock %}